### ISSUE TITLE
Nexus.core issue

### ISSUE THREAD

**Issue by technobbrace** [nexussays/core#2]
Hi,

It's about three days that I can't install my app on my phone because it's showing me this error:

/Users/ccc/Downloads/ccc/ccc.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Boolean nexus.core.Bytes::IsNullOrEmptyOrNullByte(System.Byte[])', referenced from the method 'System.Void nexus.protocols.ble.BleAdvertisement::UpdateFromRawData(System.Collections.Generic.IList`1<nexus.protocols.ble.scan.advertisement.AdvertisingDataItem>)' in 'nexus.core, Version=0.34.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (ccc.iOS)

can you help me?

**Comment by nexussays** [comment]
I would presume you updated to the latest version I released a few days ago and are now getting version conflicts. `ble.net` is still referencing version `0.34.0`  (see: https://www.fuget.org/packages/ble.net) so until that is updated to use the latest version you'll want to make sure any explicit references to `nexus.core` in your other projects are also using version `0.34.0` (not the latest of `0.36.0`). Then do a full clean and rebuild.

**Comment by technobbrace** [comment]
Thank you so much! Now it's working
